Feature/UI kit
NyaMilk/lessons-js-core pull request #2
Opened 2022-08-17 17:11 UTC by NyaMilk

Добрый день!
Ссылка на ui kit: https://nyamilk.github.io/lessons-js-core/page/uikit.html
Ссылка на админ панель: https://nyamilk.github.io/lessons-js-core/page/admin.html

2022-08-24 00:10 UTC, Muslik requested changes
- Некоторыелассы не по БЭМ.
- В dropdown слева checkbox. По клику на текст checkbox должен выбираться. ПО Клику на ВЕСЬ РЯД. Не должно быть отступов слева и справа.
- В dropdown справа radio. По клику на текст строка должна выбираться.
У вас сейчас отступ справа есть там.

2022-08-24 00:10 UTC, Muslik commented on page/uikit.html
> +            <input id="input-incorrect" class="custom-input__input custom-input__input_incorrect" type="text"
.custom-input__input_incorrect должен быть у оберточного div-а вместо custom-input_with-icon

2022-08-24 00:10 UTC, Muslik commented on page/uikit.html
> +        <div class="custom-input custom-input_with-icon">
Цвет placeholder не как на макете

2022-08-24 00:10 UTC, Muslik commented on page/uikit.html
> +            <button class="custom-button__button custom-button__button_size_middle custom-button__button_disabled"
Во первых тут не родителя - custom-button чтобы кнопка стала элементом.
Во вторых, кнопка - самостоятельный блок. ```.button```

2022-08-24 00:10 UTC, Muslik commented on page/uikit.html
> +                <svg class="custom-button__icon custom-button__icon_stroke_blue" viewBox="0 0 16 16"
Класс иконки берите из класса выше:
```.button_transparent .button__icon```

2022-08-24 00:10 UTC, Muslik commented on page/uikit.html
> +            <button class="custom-button__button custom-button__button_size_middle custom-button__button_transparent">
Приписка custom абсолютно лишняя

2022-08-24 07:08 UTC, NyaMilk commented on page/uikit.html
> +            <input id="input-incorrect" class="custom-input__input custom-input__input_incorrect" type="text"
Поправила, также сделала и для disabled (.custom-input_disabled)

2022-08-24 07:08 UTC, NyaMilk commented on page/uikit.html
> +        <div class="custom-input custom-input_with-icon">
Добавила цвет

2022-08-24 07:10 UTC, NyaMilk commented on page/uikit.html
> +            <button class="custom-button__button custom-button__button_size_middle custom-button__button_disabled"
Поправила на .button

2022-08-24 07:11 UTC, NyaMilk commented on page/uikit.html
> +                <svg class="custom-button__icon custom-button__icon_stroke_blue" viewBox="0 0 16 16"
Поправила все классы в дочерних элементах button

2022-08-24 07:12 UTC, NyaMilk commented on page/uikit.html
> +            <button class="custom-button__button custom-button__button_size_middle custom-button__button_transparent">
Поправила класса на button

2022-08-27 22:22 UTC, Muslik approved these changes
Парочка замечаний. Будут в видео

2022-09-01 21:55 UTC, merged